name: "Deploy to AWS S3"
description: "Deploy website via AWS S3."
inputs:
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default: "true"
runs:
  using: "node16"
  main: "main.js"
