import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ProvidersWrapper } from "./providers-wrapper";
import { NavLinks } from "./ui/nav-links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Renders the root layout of the application.
 *
 * @param {React.ReactNode} props.children - The children components to be rendered within the layout.
 * @return {JSX.Element} The root layout component.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersWrapper>
          <NavLinks />
          <main>{children}</main>
          <ToastContainer />
        </ProvidersWrapper>
      </body>
    </html>
  );
}
