import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavLinks } from "./ui/nav-links";
import { ActivitiesProvider } from "./context/activities-context";
import { SavedRoutesProvider } from "./context/saved-routes-context";
import { QueryProvider } from "./query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ActivitiesProvider>
          <SavedRoutesProvider>
            <QueryProvider>
              <NavLinks />
              <main>{children}</main>
            </QueryProvider>
          </SavedRoutesProvider>
        </ActivitiesProvider>
      </body>
    </html>
  );
}
