name: Deploy

on:
  push:
    branches:
      - master

env:
  STRAVA_API_BASE_URL: https://www.strava.com

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Run linters
        run: |
          npm run lint
          npm run lint-next
