name: Run tests and deploy on push
on: [push, workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo '${{ toJSON(github) }}'
